server:
  port: 8080

spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      routes:
      - id: routeClockIn
        uri: lb://toclockin
        predicates:
        - Path=/toclockin/**
      - id: routeOauth
        uri: lb://oauth-api
        predicates:
        - Path=/oauth/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    discovery:
      enabled: true

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka