spring:
  application:
    name: toclockin
  datasource:
    url: jdbc:mariadb://localhost:3306/toclockindb?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: root

server:
  port: 8080