spring:
  application:
    name: oauth-api

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

server:
  port: ${PORT:0}

jwt:
  secret: jwt-secret

oauth:
  client:
    name: toclockin
    secret: toclockin-secret
